config/routes.rb
Rails.application.routes.draw do
  resources :audit_logs, except: [:edit, :new, :destroy] do 
    member do
      get :confirm
    end
  end  
  namespace :admin do
    # resources :users
    resources :posts
    resources :admin_users
    resources :employees
    root to: "employees#index"
  end

  resources :posts do 
    member do
      get :approve
    end  
  end    
  devise_for :users, skip: [:registrations]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  authenticated :user do
    root to: 'statics#welcome', as: :authenticated_root
  end
  root to: redirect('/users/sign_in')
end

app/views/shared/_alerts.html.erb
<% flash.each do |name,msg| %>
  <script type="text/javascript">
   <% if  flash[:error]%>
     toastr['error']('there is an error');
   <%elsif flash[:alert]%>
     toastr['info']('<%= msg %>');
   <% else flash[:success]  %>
     toastr['success']('<%= msg %>');
   <% end %>  
  </script>
<% end %>  

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
   <div class="row">
	  <div class="col-md-offset-2 col-md-8">
	       
	        <div class = "panel panel-danger">
			   <div class = "panel-heading">
			      <h4>
				      <% num_error=pluralize(obj.errors.count, "error") %> 
				      There are <%= num_error %>
			      </h4>
			   </div>
			   
			   <div class = "panel-body">
			      <ul>
				      <% obj.errors.full_messages.each do |msg| %>
				      <li><%= msg %></li>
				      <% end %>
			      </ul>
			   </div>
		    </div>
	   </div>	  
	</div>
<% end %>	

app/views/shared/_nav.html.erb
<%if current_user %>
	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <%= link_to "OVERTIME TRACK", root_path, class: "navbar-brand", id: "logo" %>
	       
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	       <li class= <%= active?(root_path) %> >
				   <%= link_to "Home", root_path %>
			   </li>
	       <% if employee? %>
		       <li class= <%= active?(posts_path) %> >
					   <%= link_to "Time Trackers", posts_path %>
				   </li>
		       <li class= <%= active?(new_post_path) %> >
						<%= link_to "New Entry", new_post_path, id: "new_post_from_nav"  %>
					 </li>
				 <% end %>	 
				 <% if admin? %>	 
					 <li class= <%= active?(audit_logs_path) %> >
						<%= link_to "Audit Logs", audit_logs_path, id: "audit_logs_from_nav"  %>
					 </li>
			   <% end %>  
	      </ul>
	       
	      <ul class="nav navbar-nav navbar-right">
	        
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
	          <ul class="dropdown-menu">
	            <% if admin?  %>
					      <li>
						      <%= link_to "Admin", admin_root_path %> 
						    </li> 
						    <li class="divider"></li>
					      
					    <% end %>	
					    <li>
						   <%= link_to "Logout", destroy_user_session_path, method: :delete %> 
					    </li>
	          </ul>
	        </li>
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>
<% end %>