config/routes.rb
Rails.application.routes.draw do
  resources :audit_logs, except: [:edit, :new, :destroy] do 
    member do
      get :confirm
    end
  end  
  namespace :admin do
    # resources :users
    resources :posts
    resources :admin_users
    resources :employees
    root to: "employees#index"
  end

  resources :posts do 
    member do
      get :approve
    end  
  end    
  devise_for :users, skip: [:registrations]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  authenticated :user do
    root to: 'statics#welcome', as: :authenticated_root
  end
  root to: redirect('/users/sign_in')
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController

	def welcome
		if admin_types.include?(current_user.try(:type))
			@pending_approvals=Post.submitted
	    @audit_log=AuditLog.last(10)
	  else
	    @pending_audits= current_user.audit_logs.pending
	  end    
	end	
end

app/views/statics/_admin.html.erb
 
<div class="container-fluid">
 <div class= "pending-overtime-approval row center">
	 <h2>Items Pending Your Approval</h2>
	  <% @pending_approvals.each do |pending_approval| %>
			<div class="homepage-block col-md-3">
			  <h4>
			    <%= pending_approval.user.full_name %>
			 </h4>
			  <span class="pending-details"> Date Submitted:</span> <%= pending_approval.date %>
			  <span class="pending-details"> rationale:</span> <%= truncate pending_approval.rationale, length: 42 %> 
			 
				<div class="row">
					<div class="col-md-6">
		        <%= link_to "Approve", approve_post_path(pending_approval), class: "btn btn-success btn-block", id:"approve_#{pending_approval.id}" %>
					</div>
					<div class="col-md-6">
		
					  <%= link_to "Review",  edit_admin_post_path(pending_approval), class: "btn btn-warning btn-block" %>
					</div>
				</div>
			</div>	
    <%end%>
	</div>
	<div class= "pending-overtime-approval row center">
	 <h2>Recent Audit Logs</h2>
	  <% @audit_log.each do |audit_log| %>
			<div class="homepage-block col-md-3">
			  <h4>
			    <%= audit_log.user.full_name %>
			  </h4>
			  <span class="pending-details"> Week Starting:</span> <%=  audit_log.start_date %>
			  <span class="pending-details"> confirmed at:</span> <%=  audit_log.end_date %> 
			  <div>
			    <span class="pending-details"> status:</span> <%=  status_label audit_log.status%> 
			  </div>
		  </div>	
    <%end%>
	</div>
</div>

app/views/statics/_employee.html.erb
<div class="container-fluid">
	<div class="row">
	 <% if @pending_audits.count != 0 %>
	    <div class='pending-overtime-approval employee-blocks'>
		    <h3>Pending your confirmation</h3>
			  <% @pending_audits.each do |pending_audits|%>  
			    <%= link_to "I CONFIRM THAT I DID NOT PERFORM ANY OVERTIME FOR THIS WEEK  OF: #{pending_audits.start_date} to #{pending_audits.start_date + 6.days}", confirm_audit_log_path(pending_audits), class: "btn btn-lg btn-primary btn-block btn-employee-home",style: "margin-bottom:4px; word-wrap:break-word;", data: {confirm: "confirm are you sure?"}%>
			  <% end %>    
	    </div> 
   <% end %>
   <div class='pending-overtime-approval employee-blocks'> 
      <h3>New Requests</h3>
      <%= link_to "Create New Overtime Request",new_post_path, class: "btn btn-lg btn-primary btn-block  "%>
   </div>

  </div>
</div>

app/views/statics/welcome.html.erb
<% if admin_types.include?(current_user.try(:type)) %>
  <%= render "admin" %>
<% elsif %>
  <%= render "employee" %>
<% else %>
  redirect_to new_user_session  
<% end %>  