config/routes.rb
Rails.application.routes.draw do
  resources :audit_logs, except: [:edit, :new, :destroy] do 
    member do
      get :confirm
    end
  end  
  namespace :admin do
    # resources :users
    resources :posts
    resources :admin_users
    resources :employees
    root to: "employees#index"
  end

  resources :posts do 
    member do
      get :approve
    end  
  end    
  devise_for :users, skip: [:registrations]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  authenticated :user do
    root to: 'statics#welcome', as: :authenticated_root
  end
  root to: redirect('/users/sign_in')
end

app/models/post.rb
class Post < ApplicationRecord
	paginates_per 5
	enum status: {submitted: 0, approved: 1, rejected: 2}
	belongs_to :user
  validates_presence_of :date, :rationale, :overtime_request
  validates :overtime_request, numericality: { greater_than: 0.0}
  scope :posts_by, ->(user){ where(user_id: user.id)}

  after_save :approve_audit_log , if: :submitted?
  after_save :unapprove_audit_log , if: :rejected?

  private
    def approve_audit_log
			audit_log = AuditLog.where(user_id: self.user_id, start_date: (self.date - 7.days..self.date)).last
			audit_log.approved! if audit_log
		end
		def unapprove_audit_log
      audit_log = AuditLog.where(user_id: self.user_id, start_date: (self.date - 7.days..self.date)).last
			audit_log.pending! if audit_log
		end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Post.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Post.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :approve]
  def index
    @posts = current_user.posts.page params[:page]
  end	

  def approve
    authorize @post
    @post.approved!
    redirect_to root_path, notice:"your post has been approved"
  end

  def new
    @post = Post.new
  end	

  def create
    @post = Post.new(require_params)
    @post.user_id =  current_user.id
    
    if @post.save
      redirect_to  @post, notice: "your post was created successfully"
    else
      render "new"
    end    
  end	

  def show
    authorize @post
  end

  def edit
    authorize @post
  end  

  def update
    authorize @post
    if @post.update(require_params)
      redirect_to @post, notice: "your post was created succesfully"
    else
      render "edit"
    end  
  end  

  def destroy
    authorize @post
    @post.delete
    redirect_to posts_path, notice: "your post was deleted succesfully" 
  end  

  private
    def require_params
      params.require(:post).permit(:date, :rationale, :overtime_request) 
    end 

    def set_post
      @post = Post.find(params[:id])
    end   	
end

app/helpers/posts_helper.rb
module PostsHelper
   
end

app/views/posts/_form.html.erb
<%= render"shared/errors", obj: @post %> 
<%= form_for @post, class: "form-horizontal"  do |f|  %>
  <div class="form-group">	
	  <%= f.label :overtime_request, class: "col-sm-2" %> 
	  <%= f.text_field :overtime_request, class: "form-control" %>
	</div>   
	<div class="form-group"> 
	  <%= f.label :date, class: "col-sm-2" %>
		<%= f.date_field :date,  class: "form-control"%>
	</div>
	<div class="form-group">	
	  <%= f.label :rationale, class: "col-sm-2" %> 
	  <%= f.text_area :rationale, class: "form-control" %>
	</div>
	  
	  <%= f.submit class: "btn btn-default btn-primary btn-block" %>
   
<% end %>		
 


 

app/views/posts/_post.html.erb
<tr>
	<td>
		<%= post.id%>
	</td>
	<td>
		<%= post.date %>
	</td>
	<td>
		<%= post.overtime_request %>
	</td>
	<td>
		<%=  post.user.full_name %>	 
	</td>
	<td>
	  <%=   link_to truncate(post.rationale, length: 10), post %>
	</td>
	<td>
	  <%= status_label post.status %>
	</td>
	<td>
	  <%=   link_to "",  edit_post_path(post), id: "Edit_#{post.id}", class: "glyphicon glyphicon-edit icon-value black-hover" if policy(post).update? %>
	 
	  <%=   link_to "",  post_path(post), method: :delete, id: "delete_post_#{post.id}_from_index", class: " glyphicon glyphicon-trash icon-value red-hover" , data: {confirm: "confirm are you sure?"} %>
	</td>
</tr>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render "form" %>

app/views/posts/index.html.erb
<h3> List of Posts </h3>
<div align="center" id="paginator"> 
<%= paginate @posts, remote: true %>
</div>
<table class="table table-hover table-striped">
	<thead>
		<tr>
			<th>
				#
			</th>
			<th>
				DATE
			</th>
			<th>
				Overtime
			</th>
			<th>
				USER
			</th>

			<th>
				RATIONALE
			</th>
			<th>
			  STATUS
			</th>
			<th>
			  ACTIONS
			</th>
			 

		</tr>
	</thead>


	<tbody id= "posts">
	 <%= render @posts %>          
		 
	</tbody>
</table>
<div align="center" id="paginator1"> 
<%= paginate @posts, remote: true %>
</div>
 
 

app/views/posts/index.js.erb
$('#posts').html('<%= escape_javascript render(@posts) %>');
$('#paginator').html('<%= escape_javascript(paginate(@posts, remote: true).to_s) %>');
$('#paginator1').html('<%= escape_javascript(paginate(@posts, remote: true).to_s) %>');

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render "form" %>

app/views/posts/show.html.erb
 

<div>
<h2><%= @post.rationale %></h2>
</div>
<hr>
<div class="well">
 <h3> 
	<div><span>Overtime requested:</span><%= @post.overtime_request%></div>
	<div><span>Employee:</span><%= @post.user.full_name %></div>
	<div><span>Date:</span><%= @post.date %></div>
	<div><span>Current Stage of Approval:</span><%= @post.status %></div>
 </h3>
 <%=   link_to "",  edit_post_path(@post)  , class: "glyphicon glyphicon-edit icon-value black-hover" if policy(@post).update? %>
	 
	  <%=   link_to "",  post_path(@post), method: :delete, class: " glyphicon glyphicon-trash icon-value red-hover" , data: {confirm: "confirm are you sure?"} %>
</div>
 